### ISSUE TITLE
ClassNotFoundException on AdminConfigHolder

### ISSUE THREAD

**Issue by amfgit** [kaleidos/grails-admin-interface#25]
Hi, I'm having a ClassNotFoundException on AdminConfigHolder on _processsDomainConfig:186 - def clazz = Class.forName(domainConfig)

Maybe this would help: http://binarybuffer.com/2012/03/grails-class-forname-classnotfoundexception

I'm using Grails 2.2.2, admin-interface:0.6.5 and spring-security-core:1.2.7.3

Thanks!

**Comment by pabloalba** [comment]
Thank you, I'll check this soon :)

**Comment by pabloalba** [comment]
You're right!

This doesn't happen on latest grails version, but it does on 2.2.2

I just fixed it on github, and now I will publish a new release of the plugin

Thank you!
