### ISSUE TITLE
RelationPopupWidgetList has no paging for itemcount between 10 and 20

### ISSUE THREAD

**Issue by vhaas** [kaleidos/grails-admin-interface#26]
If the item count for the RelationPopupWidgetList is between 10 and 20 ``<ul class="pagination">`` is not shown. (One-to-many) - Relation

**Comment by vhaas** [comment]
``<ul>``

**Comment by pabloalba** [comment]
Fixed! We will release a new version soon. Thank you!

**Comment by pabloalba** [comment]
Done! https://twitter.com/grailsplugins/status/565853803484704768
